# Generated by Django 4.0.4 on 2022-05-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_event_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contract',
        ),
    ]
