# Generated by Django 4.0.4 on 2022-05-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_client_date_created_alter_client_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateTimeField(),
        ),
    ]
